### ISSUE TITLE
Need documentation on how to use 3DLinker with new data

### ISSUE THREAD

**Issue by heathcliff233** [YinanHuang/3DLinker#1]
Hello Yinan, thank you for the awesome work! I am trying to use 3DLinker on a few toy examples of fragments, but there seems not to be instructions on how to use it with customized fragments. Would you please share the step-to-step workflow of using 3DLinker with two fragments in SMILES string as input? Thank you.
ps. I went through the instructions given by DeLinker, but there are still differences between.

**Comment by FeilongWuHaa** [comment]
You can refer to the following link: https://github.com/fimrie/DeLinker/blob/master/examples/DeLinker_scaffold_hopping.ipynb

3DLinker prepare molecular data in ways of Delinker

**Comment by YinanHuang** [comment]
Thanks for the suggestion! Instruction on preparing customized dataset is now available: kindly see the README under directory zinc.
