### ISSUE TITLE
Code Recurrence Problem About 3DLinker

### ISSUE THREAD

**Issue by LWBKeeper** [YinanHuang/3DLinker#2]
Hello, author. We have some problems in reproducing your code. Now I want to ask why. After generating connector molecules with your pre trained model, we run the evaluation function. The results of some indicators in the front are OK, but in the final filter detection, the results are all zero. We don't understand why. We hope we can wait for your help. Thank you!

**Comment by YinanHuang** [comment]
It is due to a missing file "fpscores.pkl.gz" under analysis. Now it is added and the filtering should work. Thanks!

**Comment by LWBKeeper** [comment]
With your help, we have solved this problem very well. Thank you.
